[pytest]
addopts =  --alluredir=./allure-results --clean-alluredir
markers = e2e: for end to end flow testing of booking api
          crud: for CRUD testing of booking api endpoints
          DDT: for data driven test of create token api